# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gauth": "99c_data_manage.DLMusic_Data.ipynb",
         "cred_fpath": "99b_data_manage.gdrive_interact.ipynb",
         "drive": "99c_data_manage.DLMusic_Data.ipynb",
         "gtypes": "99c_data_manage.DLMusic_Data.ipynb",
         "get_root_remote_id": "99c_data_manage.DLMusic_Data.ipynb",
         "get_folder_id": "99c_data_manage.DLMusic_Data.ipynb",
         "grab_folder_contents": "99c_data_manage.DLMusic_Data.ipynb",
         "check_file_exists_remote": "99c_data_manage.DLMusic_Data.ipynb",
         "get_file_id": "99c_data_manage.DLMusic_Data.ipynb",
         "download_file": "99c_data_manage.DLMusic_Data.ipynb",
         "upload_new_file": "99c_data_manage.DLMusic_Data.ipynb",
         "update_existing_file": "99c_data_manage.DLMusic_Data.ipynb",
         "sync_file_to_remote": "99c_data_manage.DLMusic_Data.ipynb"}

modules = ["local_repo_path.py",
           "data_manage/gdrive_interact.py",
           "repo_management/DLMusic_Data.py"]

doc_url = "https://seanczak.github.io/ml/"

git_url = "https://github.com/seanczak/ml/tree/{branch}/"

def custom_doc_links(name): return None
