# AUTOGENERATED! DO NOT EDIT! File to edit: util_nbs/99a_local_repo_path.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os

# Cell
try:
    # path of the current py file that the nb exports into (not the notebook)
    file_path = os.path.dirname(os.path.realpath(__file__))
    # abs path to collection repo in your computer
    local_repo_path = file_path[:-2] # this could be cleaner, see below
except:
    print('in a notebook environment')